### ISSUE TITLE
export anm.hkx

### ISSUE THREAD

**Issue by RyckoTheAngel** [blueskythlikesclouds/HavokAnimationExporter#1]
Me podrias ayudar en la exportacion de animacion de sonic generations, no entendí nada de las instrucciones

Could you help me export the animation from Sonic Generations, I didn't understand anything about the instructions
[sn_boost_loop.anm.zip](https://github.com/blueskythlikesclouds/HavokAnimationExporter/files/15089625/sn_boost_loop.anm.zip)

**Comment by blueskythlikesclouds** [comment]
What did you not understand exactly? You drag & drop the .FBX file onto the .BAT file. Make sure the .skl.hkx file is next to the .bat file, as well. Edit the .bat file if the file name in it does not match with the name of your .skl.hkx file.

**Comment by RyckoTheAngel** [comment]
Do you have an example of how to have the .bat file and how to have the .skl.hkx and also the .fbx?

I tried dragging sn_boost_loop.fbx and it just came out sn_boost_loop.skl.hkx and not sn_boost_loop.anm.hkx

________________________________

**Comment by RyckoTheAngel** [comment]
Es que soy de Latinoamérica y pues al tratar de traducir con el traductor de Google me aparece en forma semi entendible.

The thing is that I am from Latin America and when I try to translate with Google Translate it appears in a semi-understandable form.
________________________________

**Comment by blueskythlikesclouds** [comment]
https://github.com/blueskythlikesclouds/HavokAnimationExporter/assets/19259897/140f06e8-2440-46e0-abc2-4d56509c09ed

**Comment by RyckoTheAngel** [comment]
And can I do it vice versa? I mean from .anm.fbx to .anm.hkx?

**Comment by blueskythlikesclouds** [comment]
That video already shows .anm.fbx to .anm.hkx?

**Comment by RyckoTheAngel** [comment]
Ha

**Comment by RyckoTheAngel** [comment]
Sorry🥲😅

**Comment by RyckoTheAngel** [comment]
Vales 1,000<3

**Comment by RyckoTheAngel** [comment]
<3 It's a heart, don't think wrong

**Comment by blueskythlikesclouds** [comment]
Uh sure.
Feel free to close this issue if you solved your problem.

**Comment by RyckoTheAngel** [comment]
Ok, I can still send you another one if I have a problem, right?
